# Workflow to restrict main branch to pull requests from develop branch.
# ref: https://stackoverflow.com/questions/46495855/restrict-branch-x-to-be-merged-only-from-one-specific-branch-y-in-github

name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ! ${GITHUB_HEAD_REF} =~ ^release/  ]] && [[ ! ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
          then
            echo "Error: Pull request must come from 'release/' or 'hotfix/' branch" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
